const TermActionTypes = {
    FETCH_TERMS: "FETCH_TERMS",
    FETCH_TERMS_SUCCESS: "FETCH_TERMS_SUCCESS",
    FETCH_TERMS_FAILURE: "FETCH_TERMS_FAILURE",

    FETCH_TERM: "FETCH_TERM",
    FETCH_TERM_SUCCESS: "FETCH_TERM_SUCCESS",
    FETCH_TERM_FAILURE: "FETCH_TERM_FAILURE",

    UPDATE_TERM: "UPDATE_TERM",
    UPDATE_TERM_SUCCESS: "UPDATE_TERM_SUCCESS",
    UPDATE_TERM_FAILURE: "UPDATE_TERM_FAILURE",

    CREATE_TERM: "CREATE_TERM",
    CREATE_TERM_SUCCESS: "CREATE_TERM_SUCCESS",
    CREATE_TERM_FAILURE: "CREATE_TERM_FAILURE",

    DELETE_TERM: "DELETE_TERM",
    DELETE_TERM_SUCCESS: "DELETE_TERM_SUCCESS",
    DELETE_TERM_FAILURE: "DELETE_TERM_FAILURE",

    FETCH_STUDENTS_FOR_TERM: "FETCH_STUDENTS_FOR_TERM",
    FETCH_STUDENTS_FOR_TERM_SUCCESS: "FETCH_STUDENTS_FOR_TERM_SUCCESS",
    FETCH_STUDENTS_FOR_TERM_FAILURE: "FETCH_STUDENTS_FOR_TERM_FAILURE",

    DELETE_STUDENT_FROM_TERM: "DELETE_STUDENT_FROM_TERM",
    DELETE_STUDENT_FROM_TERM_SUCCESS: "DELETE_STUDENT_FROM_TERM_SUCCESS",
    DELETE_STUDENT_FROM_TERM_FAILURE: "DELETE_STUDENT_FROM_TERM_FAILURE",
};

export default TermActionTypes;
