const DivisionActionTypes = {
    FETCH_DIVISIONS: "FETCH_DIVISIONS",
    FETCH_DIVISIONS_SUCCESS: "FETCH_DIVISIONS_SUCCESS",
    FETCH_DIVISIONS_FAILURE: "FETCH_DIVISIONS_FAILURE",

    DELETE_DIVISION: "DELETE_DIVISION",
    DELETE_DIVISION_SUCCESS: "DELETE_DIVISION_SUCCESS",
    DELETE_DIVISION_FAILURE: "DELETE_DIVISION_FAILURE",

    FETCH_DIVISION: "FETCH_DIVISION",
    FETCH_DIVISION_SUCCESS: "FETCH_DIVISION_SUCCESS",
    FETCH_DIVISION_FAILURE: "FETCH_DIVISION_FAILURE",

    CREATE_DIVISION: "CREATE_DIVISION",
    CREATE_DIVISION_SUCCESS: "CREATE_DIVISION_SUCCESS",
    CREATE_DIVISION_FAILURE: "CREATE_DIVISION_FAILURE",

    UPDATE_DIVISION: "UPDATE_DIVISION",
    UPDATE_DIVISION_SUCCESS: "UPDATE_DIVISION_SUCCESS",
    UPDATE_DIVISION_FAILURE: "UPDATE_DIVISION_FAILURE",

    FETCH_STUDENTS_FOR_SELECTED_DIVISION: "FETCH_STUDENTS_FOR_SELECTED_DIVISION",
    FETCH_STUDENTS_FOR_SELECTED_DIVISION_SUCCESS: "FETCH_STUDENTS_FOR_SELECTED_DIVISION_SUCCESS",
    FETCH_STUDENTS_FOR_SELECTED_DIVISION_FAILURE: "FETCH_STUDENTS_FOR_SELECTED_DIVISION_FAILURE",

    DELETE_STUDENT_FROM_SELECTED_DIVISION: "DELETE_STUDENT_FROM_SELECTED_DIVISION",
    DELETE_STUDENT_FROM_SELECTED_DIVISION_SUCCESS: "DELETE_STUDENT_FROM_SELECTED_DIVISION_SUCCESS",
    DELETE_STUDENT_FROM_SELECTED_DIVISION_FAILURE: "DELETE_STUDENT_FROM_SELECTED_DIVISION_FAILURE",

    ADD_STUDENTS_TO_SELECTED_DIVISION: "ADD_STUDENTS_TO_SELECTED_DIVISION",
    ADD_STUDENTS_TO_SELECTED_DIVISION_SUCCESS: "ADD_STUDENTS_TO_SELECTED_DIVISION_SUCCESS",
    ADD_STUDENTS_TO_SELECTED_DIVISION_FAILURE: "ADD_STUDENTS_TO_SELECTED_DIVISION_FAILURE",
};

export default DivisionActionTypes;
