const SchoolActionTypes = {
    FETCH_SCHOOLS: "FETCH_SCHOOLS",
    FETCH_SCHOOLS_SUCCESS: "FETCH_SCHOOLS_SUCCESS",
    FETCH_SCHOOLS_FAILURE: "FETCH_SCHOOLS_FAILURE",

    FETCH_SCHOOL: "FETCH_SCHOOL",
    FETCH_SCHOOL_SUCCESS: "FETCH_SCHOOL_SUCCESS",
    FETCH_SCHOOL_FAILURE: "FETCH_SCHOOL_FAILURE",

    FETCH_SCHOOL_TIME_SLOTS: "FETCH_SCHOOL_TIME_SLOTS",
    FETCH_SCHOOL_TIME_SLOTS_SUCCESS: "FETCH_SCHOOL_TIME_SLOTS_SUCCESS",
    FETCH_SCHOOL_TIME_SLOTS_FAILURE: "FETCH_SCHOOL_TIME_SLOTS_FAILURE",

    UPDATE_SCHOOL: "UPDATE_SCHOOL",
    UPDATE_SCHOOL_SUCCESS: "UPDATE_SCHOOL_SUCCESS",
    UPDATE_SCHOOL_FAILURE: "UPDATE_SCHOOL_FAILURE",

    CREATE_SCHOOL: "CREATE_SCHOOL",
    CREATE_SCHOOL_SUCCESS: "CREATE_SCHOOL_SUCCESS",
    CREATE_SCHOOL_FAILURE: "CREATE_SCHOOL_FAILURE",

    DELETE_SCHOOL: "DELETE_SCHOOL",
    DELETE_SCHOOL_SUCCESS: "DELETE_SCHOOL_SUCCESS",
    DELETE_SCHOOL_FAILURE: "DELETE_SCHOOL_FAILURE",
};

export default SchoolActionTypes;
