const FileActionTypes = {
    FETCH_FILES: "FETCH_FILES",
    FETCH_FILES_SUCCESS: "FETCH_FILES_SUCCESS",
    FETCH_FILES_FAILURE: "FETCH_FILES_FAILURE",

    FETCH_FILES_COURSE: "FETCH_FILES_COURSE",
    FETCH_FILES_COURSE_SUCCESS: "FETCH_FILES_COURSE_SUCCESS",
    FETCH_FILES_COURSE_FAILURE: "FETCH_FILES_COURSE_FAILURE",

    FETCH_FILE: "FETCH_FILE",
    FETCH_FILE_SUCCESS: "FETCH_FILE_SUCCESS",
    FETCH_FILE_FAILURE: "FETCH_FILE_FAILURE",

    UPLOAD_FILE: "UPLOAD_FILE",
    UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
    UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",

    UPDATE_FILE: "UPDATE_FILE",
    UPDATE_FILE_SUCCESS: "UPDATE_FILE_SUCCESS",
    UPDATE_FILE_FAILURE: "UPDATE_FILE_FAILURE",

    FETCH_FILES_SUBMISSION_ID: "FETCH_FILES_SUBMISSION_ID",
    FETCH_FILES_SUBMISSION_ID_SUCCESS: "FETCH_FILES_SUBMISSION_ID_SUCCESS",
    FETCH_FILES_SUBMISSION_ID_FAILURE: "FETCH_FILES_SUBMISSION_ID_FAILURE",
};

export default FileActionTypes;
