const AdminActionTypes = {
    FETCH_ADMINS: "FETCH_ADMINS",
    FETCH_ADMINS_SUCCESS: "FETCH_ADMINS_SUCCESS",
    FETCH_ADMINS_FAILURE: "FETCH_ADMINS_FAILURE",

    UPDATE_ADMIN: "UPDATE_ADMIN",
    UPDATE_ADMIN_SUCCESS: "UPDATE_ADMIN_SUCCESS",
    UPDATE_ADMIN_FAILURE: "UPDATE_ADMIN_FAILURE",

    FETCH_ADMIN_ME: "FETCH_ADMIN_ME",
    FETCH_ADMIN_ME_SUCCESS: "FETCH_ADMIN_ME_SUCCESS",
    FETCH_ADMIN_ME_FAILURE: "FETCH_ADMIN_ME_FAILURE",

    FETCH_ADMIN: "FETCH_ADMIN",
    FETCH_ADMIN_SUCCESS: "FETCH_ADMIN_SUCCESS",
    FETCH_ADMIN_FAILURE: "FETCH_ADMIN_FAILURE",
};

export default AdminActionTypes;
