const AdminActionTypes = {
    FETCH_ADMIN_ME: "FETCH_ADMIN_ME",
    FETCH_ADMIN_ME_SUCCESS: "FETCH_ADMIN_ME_SUCCESS",
    FETCH_ADMIN_ME_FAILURE: "FETCH_ADMIN_ME_FAILURE",
};

export default AdminActionTypes;
