const CourseActionTypes = {
    FETCH_COURSES: "FETCH_COURSES",
    FETCH_COURSES_SUCCESS: "FETCH_COURSES_SUCCESS",
    FETCH_COURSES_FAILURE: "FETCH_COURSES_FAILURE",

    CREATE_COURSE: "CREATE_COURSE",
    CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
    CREATE_COURSE_FAILURE: "CREATE_COURSE_FAILURE",

    FETCH_COURSE: "FETCH_COURSE",
    FETCH_COURSE_SUCCESS: "FETCH_COURSE_SUCCESS",
    FETCH_COURSE_FAILURE: "FETCH_COURSE_FAILURE",

    UPDATE_COURSE: "UPDATE_COURSE",
    UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
    UPDATE_COURSE_FAILURE: "UPDATE_COURSE_FAILURE",

    DELETE_COURSE: "DELETE_COURSE",
    DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
    DELETE_COURSE_FAILURE: "DELETE_COURSE_FAILURE",
};

export default CourseActionTypes;
