const TimetableActionTypes = {
    FETCH_TIMETABLE: "FETCH_TIMETABLE",
    FETCH_TIMETABLE_SUCCESS: "FETCH_TIMETABLE_SUCCESS",
    FETCH_TIMETABLE_FAILURE: "FETCH_TIMETABLE_FAILURE",

    FETCH_TIMETABLE_DIVISION: "FETCH_TIMETABLE_DIVISION",
    FETCH_TIMETABLE_DIVISION_SUCCESS: "FETCH_TIMETABLE_DIVISION_SUCCESS",
    FETCH_TIMETABLE_DIVISION_FAILURE: "FETCH_TIMETABLE_DIVISION_FAILURE",

    FETCH_LECTURE: "FETCH_LECTURE",
    FETCH_LECTURE_SUCCESS: "FETCH_LECTURE_SUCCESS",
    FETCH_LECTURE_FAILURE: "FETCH_LECTURE_FAILURE",

    CREATE_LECTURE: "CREATE_LECTURE",
    CREATE_LECTURE_SUCCESS: "CREATE_LECTURE_SUCCESS",
    CREATE_LECTURE_FAILURE: "CREATE_LECTURE_FAILURE",

    UPDATE_LECTURE: "UPDATE_LECTURE",
    UPDATE_LECTURE_SUCCESS: "UPDATE_LECTURE_SUCCESS",
    UPDATE_LECTURE_FAILURE: "UPDATE_LECTURE_FAILURE",
};

export default TimetableActionTypes;
