const TimetableActionTypes = {
    FETCH_TIMETABLE: "FETCH_TIMETABLE",
    FETCH_TIMETABLE_SUCCESS: "FETCH_TIMETABLE_SUCCESS",
    FETCH_TIMETABLE_FAILURE: "FETCH_TIMETABLE_FAILURE",
    FETCH_TIMETABLE_DIVISION: "FETCH_TIMETABLE_DIVISION",
    FETCH_TIMETABLE_DIVISION_SUCCESS: "FETCH_TIMETABLE_DIVISION_SUCCESS",
    FETCH_TIMETABLE_DIVISION_FAILURE: "FETCH_TIMETABLE_DIVISION_FAILURE",
};

export default TimetableActionTypes;
