const YearActionTypes = {
    FETCH_YEARS: "FETCH_YEARS",
    FETCH_YEARS_SUCCESS: "FETCH_YEARS_SUCCESS",
    FETCH_YEARS_FAILURE: "FETCH_YEARS_FAILURE",

    FETCH_YEAR: "FETCH_YEAR",
    FETCH_YEAR_SUCCESS: "FETCH_YEAR_SUCCESS",
    FETCH_YEAR_FAILURE: "FETCH_YEAR_FAILURE",

    UPDATE_YEAR: "UPDATE_YEAR",
    UPDATE_YEAR_SUCCESS: "UPDATE_YEAR_SUCCESS",
    UPDATE_YEAR_FAILURE: "UPDATE_YEAR_FAILURE",

    CREATE_YEAR: "CREATE_YEAR",
    CREATE_YEAR_SUCCESS: "CREATE_YEAR_SUCCESS",
    CREATE_YEAR_FAILURE: "CREATE_YEAR_FAILURE",

    DELETE_YEAR: "DELETE_YEAR",
    DELETE_YEAR_SUCCESS: "DELETE_YEAR_SUCCESS",
    DELETE_YEAR_FAILURE: "DELETE_YEAR_FAILURE",
};

export default YearActionTypes;
