const TimeSlotActionTypes = {
    FETCH_TIME_SLOTS: "FETCH_TIME_SLOTS",
    FETCH_TIME_SLOTS_SUCCESS: "FETCH_TIME_SLOTS_SUCCESS",
    FETCH_TIME_SLOTS_FAILURE: "FETCH_TIME_SLOTS_FAILURE",

    FETCH_TIME_SLOT: "FETCH_TIME_SLOT",
    FETCH_TIME_SLOT_SUCCESS: "FETCH_TIME_SLOT_SUCCESS",
    FETCH_TIME_SLOT_FAILURE: "FETCH_TIME_SLOT_FAILURE",

    UPDATE_TIME_SLOT: "UPDATE_TIME_SLOT",
    UPDATE_TIME_SLOT_SUCCESS: "UPDATE_TIME_SLOT_SUCCESS",
    UPDATE_TIME_SLOT_FAILURE: "UPDATE_TIME_SLOT_FAILURE",

    CREATE_TIME_SLOT: "CREATE_TIME_SLOT",
    CREATE_TIME_SLOT_SUCCESS: "CREATE_TIME_SLOT_SUCCESS",
    CREATE_TIME_SLOT_FAILURE: "CREATE_TIME_SLOT_FAILURE",

    DELETE_TIME_SLOT: "DELETE_TIME_SLOT",
    DELETE_TIME_SLOT_SUCCESS: "DELETE_TIME_SLOT_SUCCESS",
    DELETE_TIME_SLOT_FAILURE: "DELETE_TIME_SLOT_FAILURE",
};

export default TimeSlotActionTypes;
