const DivisionActionTypes = {
    FETCH_DIVISIONS: "FETCH_DIVISIONS",
    FETCH_DIVISIONS_SUCCESS: "FETCH_DIVISIONS_SUCCESS",
    FETCH_DIVISIONS_FAILURE: "FETCH_DIVISIONS_FAILURE",

    DELETE_DIVISION: "DELETE_DIVISION",
    DELETE_DIVISION_SUCCESS: "DELETE_DIVISION_SUCCESS",
    DELETE_DIVISION_FAILURE: "DELETE_DIVISION_FAILURE",

    FETCH_DIVISION: "FETCH_DIVISION",
    FETCH_DIVISION_SUCCESS: "FETCH_DIVISION_SUCCESS",
    FETCH_DIVISION_FAILURE: "FETCH_DIVISION_FAILURE",
};

export default DivisionActionTypes;
