const UserActionTypes = {
    FETCH_USER_ME: "FETCH_USER_ME",
    FETCH_USER_ME_SUCCESS: "FETCH_USER_ME_SUCCESS",
    FETCH_USER_ME_FAILURE: "FETCH_USER_ME_FAILURE",
    FETCH_USER:"FETCH_USER",
    FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE:"FETCH_USER_FAILURE"
}

export default UserActionTypes;