const UserActionTypes = {
    FETCH_USER_ME: "FETCH_USER_ME",
    FETCH_USER_ME_SUCCESS: "FETCH_USER_ME_SUCCESS",
    FETCH_USER_ME_FAILURE: "FETCH_USER_ME_FAILURE",

    UPDATE_USER_ME: "UPDATE_USER_ME",
    UPDATE_USER_ME_SUCCESS: "UPDATE_USER_ME_SUCCESS",
    UPDATE_USER_ME_FAILURE: "UPDATE_USER_ME_FAILURE",

    FETCH_USER: "FETCH_USER",
    FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE: "FETCH_USER_FAILURE",

    FETCH_USERS: "FETCH_USERS",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

    CREATE_USER: "CREATE_USER",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

    FETCH_PROFESSORS: "FETCH_PROFESSORS",
    FETCH_PROFESSORS_SUCCESS: "FETCH_PROFESSORS_SUCCESS",
    FETCH_PROFESSORS_FAILURE: "FETCH_PROFESSORS_FAILURE",

    FETCH_PROFESSOR_DIVISIONS: "FETCH_PROFESSOR_DIVISIONS",
    FETCH_PROFESSOR_DIVISIONS_SUCCESS: "FETCH_PROFESSOR_DIVISIONS_SUCCESS",
    FETCH_PROFESSOR_DIVISIONS_FAILURE: "FETCH_PROFESSOR_DIVISIONS_FAILURE",
};

export default UserActionTypes;
